apiVersion: v1
kind: Pod
metadata:
  name: prometheus-test
  namespace: kube-system
  labels:
    name: prometheus-test
spec:
  containers:
    - name: prometheus
      image: cargo.caicloud.io/sysinfra/prometheus:v0.0
      imagePullPolicy: Always
      env:
      - name: CLUSTER_DOMAIN
        value: cluster.local
      ports:
        - containerPort: 9090
          name: web
      volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus
      resources:
        limits:
          cpu: 2000m
          memory: 4000Mi
        requests:
          cpu: 2000m
          memory: 4000Mi
      args:
        - "-config.file=/etc/prometheus/prometheus.yml"
        - "-storage.local.path=/prometheus"
        - "-web.console.libraries=/usr/share/prometheus/console_libraries"
        - "-web.console.templates=/usr/share/prometheus/consoles"
        - "-storage.remote.opentsdb-url=http://opentsdb.default.svc:4242"
        - "-alertmanager.url=http://localhost:9093"
        - "-web.external-url=http://metrics.sysinfra.caicloudprivatetest.com:32100/"
  volumes:
    - name: prometheus-config
      configMap:
        name: prometheus-config